<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>horrible_joysticks</name>
  <version>0.0.0</version>
  <description>The goal of this package is to create some joysticks available to use in ros, which no one will ever want to use.</description>
  <maintainer email="alyn649@aucklanduni.ac.nz">angus</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>horrible_js_interfaces</exec_depend>
  <exec_depend>python3-dearpygui</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-sounddevice</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
